services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    volumes:
      - ./back:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=blackjack.settings
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"   # Match Vite default port
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0   # <-- Expose Vite server to Docker network

volumes:
  static_volume:
  media_volume:

