# Generated by Django 5.2.7 on 2025-10-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_game_created_at_player_busted'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_count',
            field=models.IntegerField(default=0),
        ),
    ]
